# HOUSE GRADE PREDICTION

### IMPORT REQUIRED LIB

In [95]:

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier

#### UOLOAD DATASET

In [96]:
df1=pd.read_csv(r'C:\Users\neeraj nandkumar\downloads\TRAINING_.csv',header=0,index_col=0)

In [97]:
df1.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO         0.0   
2           344    6.0        7.0          7.0         8.0   no         0.0   
3           294    8.0        4.0          3.0         4.0  yes        97.0   
4           328    5.0        4.0          2.0         4.0   NO         0.0   
5           295    9.0        5.0          3.0         5.0  NaN         NaN   

    Lawn(Area)  Nfloors   API  ANB Grade EXPECTED  
id                                                 
1         76.0        2  63.0    4     D    3826$  
2         83.0        7  97.0    1     B    4458$  
3         78.0        1  88.0    4     C    4199$  
4         91.0        5  86.0    1     D    3462$  
5         97.0        4  93.0    3     C    4543$

In [98]:
df1.shape

(7000, 13)

#### varifying the missing or null values

In [99]:
df1.isnull().sum()

Area(total)       0
Troom             2
Nbedrooms         3
Nbwashrooms       2
Twashrooms        1
roof           1353
Roof(Area)     1353
Lawn(Area)        2
Nfloors           0
API               1
ANB               0
Grade             0
EXPECTED          0
dtype: int64

In [100]:
df1.columns

Index(['Area(total)', 'Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms',
       'roof', 'Roof(Area)', 'Lawn(Area)', 'Nfloors', 'API', 'ANB', 'Grade',
       'EXPECTED'],
      dtype='object')

In [101]:
df1.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof            object
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
EXPECTED        object
dtype: object

#### using mean values to replace missing values

In [102]:
for value in ['Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms','Roof(Area)', 'Lawn(Area)','API']:
    df1[value].fillna(df1[value].mean(),inplace=True)

In [103]:
df1.isnull().sum()

Area(total)       0
Troom             0
Nbedrooms         0
Nbwashrooms       0
Twashrooms        0
roof           1353
Roof(Area)        0
Lawn(Area)        0
Nfloors           0
API               0
ANB               0
Grade             0
EXPECTED          0
dtype: int64

In [104]:
df1.roof.value_counts()

no     1436
NO     1419
yes    1413
YES    1379
Name: roof, dtype: int64

In [105]:
df1.roof=df1.roof.map({"yes":"YES","no":"NO","NO":"NO","YES":"YES"})
df1.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO    0.000000   
2           344    6.0        7.0          7.0         8.0   NO    0.000000   
3           294    8.0        4.0          3.0         4.0  YES   97.000000   
4           328    5.0        4.0          2.0         4.0   NO    0.000000   
5           295    9.0        5.0          3.0         5.0  NaN   47.202763   

    Lawn(Area)  Nfloors   API  ANB Grade EXPECTED  
id                                                 
1         76.0        2  63.0    4     D    3826$  
2         83.0        7  97.0    1     B    4458$  
3         78.0        1  88.0    4     C    4199$  
4         91.0        5  86.0    1     D    3462$  
5         97.0        4  93.0    3     C    4543$

#### using mode values to replace missing values

In [106]:
for value in ['roof']:
    df1[value].fillna(df1[value].mode()[0],inplace=True)

In [107]:
df1.roof.mode()[0]

'NO'

In [108]:
df1.isnull().sum()

Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Grade          0
EXPECTED       0
dtype: int64

In [109]:
df1.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof            object
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
EXPECTED        object
dtype: object

In [110]:
df1['EXPECTED'] = df1['EXPECTED'].str.replace('$', '').astype(int)

In [111]:
df1.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO    0.000000   
2           344    6.0        7.0          7.0         8.0   NO    0.000000   
3           294    8.0        4.0          3.0         4.0  YES   97.000000   
4           328    5.0        4.0          2.0         4.0   NO    0.000000   
5           295    9.0        5.0          3.0         5.0   NO   47.202763   

    Lawn(Area)  Nfloors   API  ANB Grade  EXPECTED  
id                                                  
1         76.0        2  63.0    4     D      3826  
2         83.0        7  97.0    1     B      4458  
3         78.0        1  88.0    4     C      4199  
4         91.0        5  86.0    1     D      3462  
5         97.0        4  93.0    3     C      4543

In [112]:
df1.Grade.value_counts()

C    2928
D    2129
B    1475
A     442
E      26
Name: Grade, dtype: int64

In [113]:
colname=['roof','Grade']

#### Convert the data into number using Label Encoder

In [114]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    df1[x]=le.fit_transform(df1[x])

In [115]:
df1.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           305    8.0        2.0          1.0         3.0     0    0.000000   
2           344    6.0        7.0          7.0         8.0     0    0.000000   
3           294    8.0        4.0          3.0         4.0     1   97.000000   
4           328    5.0        4.0          2.0         4.0     0    0.000000   
5           295    9.0        5.0          3.0         5.0     0   47.202763   

    Lawn(Area)  Nfloors   API  ANB  Grade  EXPECTED  
id                                                   
1         76.0        2  63.0    4      3      3826  
2         83.0        7  97.0    1      1      4458  
3         78.0        1  88.0    4      2      4199  
4         91.0        5  86.0    1      3      3462  
5         97.0        4  93.0    3      2      4543

In [116]:
df1.shape

(7000, 13)

In [117]:
for x in colname:
    df1[x]=le.fit_transform(df1[x])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature roof
mapping {0: 0, 1: 1}
Feature Grade
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}


In [118]:
change_order = ['Area(total)', 'Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms','roof',
       'Roof(Area)', 'Lawn(Area)', 'Nfloors', 'API', 'ANB','EXPECTED','Grade']
df1=df1.reindex(columns=change_order)

In [119]:
df1.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           305    8.0        2.0          1.0         3.0     0    0.000000   
2           344    6.0        7.0          7.0         8.0     0    0.000000   
3           294    8.0        4.0          3.0         4.0     1   97.000000   
4           328    5.0        4.0          2.0         4.0     0    0.000000   
5           295    9.0        5.0          3.0         5.0     0   47.202763   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  Grade  
id                                                   
1         76.0        2  63.0    4      3826      3  
2         83.0        7  97.0    1      4458      1  
3         78.0        1  88.0    4      4199      2  
4         91.0        5  86.0    1      3462      3  
5         97.0        4  93.0    3      4543      2

In [120]:
X = df1.values[:,:-1]
Y = df1.values[:,-1]

In [121]:
X.shape

(7000, 12)

In [122]:
Y.shape

(7000,)

In [123]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
print(X)

[[-0.98425512  0.69579072 -1.81044525 ... -1.34807597  0.29716957
  -0.42389823]
 [ 0.91363685 -0.71290115  1.21445694 ...  1.52094084 -1.46719601
   0.84908326]
 [-1.51955799  0.69579072 -0.60048437 ...  0.76149522  0.29716957
   0.32740255]
 ...
 [-0.93559122 -0.71290115 -0.60048437 ...  1.436558    0.29716957
  -0.4178556 ]
 [ 0.62165347  0.69579072  1.21445694 ...  0.42396383 -1.46719601
   0.9095096 ]
 [-0.54628005 -1.41724709  0.60947651 ...  1.436558   -0.87907415
  -1.24569642]]


In [124]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25,
random_state=10)

In [125]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=19, metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred))) to check the predictin list comparisan with real

In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[ 64  47   0   0   0]
 [  6 294  75   0   0]
 [  0  27 664  43   0]
 [  0   0  43 480   0]
 [  0   0   0   7   0]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.91      0.58      0.71       111
         1.0       0.80      0.78      0.79       375
         2.0       0.85      0.90      0.88       734
         3.0       0.91      0.92      0.91       523
         4.0       0.00      0.00      0.00         7

    accuracy                           0.86      1750
   macro avg       0.69      0.64      0.66      1750
weighted avg       0.86      0.86      0.85      1750

Accuracy of the model:  0.8582857142857143


In [127]:
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=1.0,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))
#Accuracy of the model:  0.9382857142857143

In [166]:
# WITH 94.54 ACCURACY
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=10,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))
#Accuracy of the model:  0.9422857142857143

In [129]:
# WITH 94.22 ACCURACY
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=10,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))

In [130]:
# WITH 0.9297142857142857 ACCURACY
from sklearn import svm
svc_model=svm.SVC(kernel='poly',C=10,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))

In [131]:
# WITH  94 ACCURACY
from sklearn.model_selection import GridSearchCV
from sklearn import svm
svc_model=svm.SVC(degree=2,C=10,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))
#Accuracy of the model:  0.9422857142857143


In [132]:
# WITH  94 ACCURACY
from sklearn import svm
svc_model=svm.SVC(kernel='linear',C=10,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))
#Accuracy of the model:   0.9017142857142857


In [133]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# Define the parameter grid to search
param_grid = {
    'C': [ 10],
    
    'degree': [2, 3],
    'coef0': [ 2],
    'class_weight': [None]
}

# Create an SVM classifier
svm = SVC()

# Use grid search with cross-validation to find the best parameters
grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, cv=5)
grid_search.fit(X_train, Y_train)

# Print the best parameters and the corresponding accuracy
print("Best Parameters: ", grid_search.best_params_)
print("Best Accuracy: {:.2f}".format(grid_search.best_score_))


# Best Accuracy: 0.94

Best Parameters:  {'C': 10, 'class_weight': None, 'coef0': 2, 'degree': 2}
Best Accuracy: 0.94


In [134]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 99  12   0   0   0]
 [  9 333  33   0   0]
 [  0  32 657  45   0]
 [  0   0  37 482   4]
 [  0   0   0   0   7]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      0.89      0.90       111
         1.0       0.88      0.89      0.89       375
         2.0       0.90      0.90      0.90       734
         3.0       0.91      0.92      0.92       523
         4.0       0.64      1.00      0.78         7

    accuracy                           0.90      1750
   macro avg       0.85      0.92      0.88      1750
weighted avg       0.90      0.90      0.90      1750

Accuracy of the model:  0.9017142857142857


In [135]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [136]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 81  30   0   0   0]
 [ 38 268  68   1   0]
 [  0  62 599  73   0]
 [  0   0  70 451   2]
 [  0   0   0   3   4]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.68      0.73      0.70       111
         1.0       0.74      0.71      0.73       375
         2.0       0.81      0.82      0.81       734
         3.0       0.85      0.86      0.86       523
         4.0       0.67      0.57      0.62         7

    accuracy                           0.80      1750
   macro avg       0.75      0.74      0.74      1750
weighted avg       0.80      0.80      0.80      1750

Accuracy of the model:  0.8017142857142857


In [137]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [138]:
# CODE REPLACE FOR TUNNING 
from sklearn.model_selection import RandomizedSearchCV

# Create a list of hyperparameter values to try
param_grid = {
    'n_estimators': [100,200],
    'max_depth': [15],
    'min_samples_split': [5],
    'min_samples_leaf': [2]
}

# Create a RandomizedSearchCV object
random_search = RandomizedSearchCV(estimator=RandomForestClassifier(), param_distributions=param_grid, n_iter=100, cv=5)

# Fit the model to the training data
random_search.fit(X_train, Y_train)

# Print the best hyperparameters
print(random_search.best_params_)

# Make predictions on the test data
y_pred = random_search.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(Y_test, Y_pred)

# Print the accuracy
print(accuracy)


{'n_estimators': 200, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_depth': 15}
0.8902857142857142


In [139]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 84  27   0   0   0]
 [  4 315  56   0   0]
 [  0  29 682  23   0]
 [  0   0  50 473   0]
 [  0   0   0   3   4]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.76      0.84       111
         1.0       0.85      0.84      0.84       375
         2.0       0.87      0.93      0.90       734
         3.0       0.95      0.90      0.93       523
         4.0       1.00      0.57      0.73         7

    accuracy                           0.89      1750
   macro avg       0.92      0.80      0.85      1750
weighted avg       0.89      0.89      0.89      1750

Accuracy of the model:  0.8902857142857142


In [140]:
# TESTING PART 

In [141]:
df2=pd.read_csv(r'C:\Users\neeraj nandkumar\downloads\TEST_.csv',header=0,index_col=0)

In [142]:
df2.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5  NaN         NaN   
2           311    6.0        5.0          5.0           6   NO         0.0   
3           342    5.0        6.0          6.0           7  yes       120.0   
4           329    7.0        7.0          4.0           6  NaN         NaN   
5           307    6.0        2.0          3.0           4   no         0.0   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [143]:
df2.shape

(3299, 12)

In [144]:
df2.isnull().sum()

Area(total)      0
Troom            1
Nbedrooms        1
Nbwashrooms      1
Twashrooms       0
roof           653
Roof(Area)     653
Lawn(Area)       1
Nfloors          0
API              1
ANB              0
EXPECTED         0
dtype: int64

In [145]:
#replace the missing values with mean values
for value in ['Troom', 'Nbedrooms', 'Nbwashrooms','Roof(Area)', 'Lawn(Area)','API']:
    df2[value].fillna(df2[value].mean(),inplace=True)

In [146]:
df2.isnull().sum()

Area(total)      0
Troom            0
Nbedrooms        0
Nbwashrooms      0
Twashrooms       0
roof           653
Roof(Area)       0
Lawn(Area)       0
Nfloors          0
API              0
ANB              0
EXPECTED         0
dtype: int64

In [147]:
df2.roof=df2.roof.map({"yes":"YES","no":"NO","NO":"NO","YES":"YES"})
df2.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5  NaN   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6  NaN   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [148]:
#replace the missing values with mode values
for value in ['roof']:
    df2[value].fillna(df2[value].mode()[0],inplace=True)

In [149]:
df2.isnull().sum()

Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
EXPECTED       0
dtype: int64

In [150]:
df2.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5   NO   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6   NO   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [151]:
df2['EXPECTED'] = df2['EXPECTED'].str.replace('$', '').astype(int)

In [152]:
df2.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5   NO   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6   NO   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  
id                                            
1         84.0        5  91.0    6      4422  
2         86.0        6  83.0    4      3432  
3         85.0        4  95.0    5      4066  
4        105.0        5  97.0    6      4322  
5         76.0        2  64.0    4      3031

In [153]:
colname=['roof']

In [154]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    df2[x]=le.fit_transform(df2[x])

In [155]:
df2.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           348    9.0        5.0          3.0           5     0   47.267196   
2           311    6.0        5.0          5.0           6     0    0.000000   
3           342    5.0        6.0          6.0           7     1  120.000000   
4           329    7.0        7.0          4.0           6     0   47.267196   
5           307    6.0        2.0          3.0           4     0    0.000000   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  
id                                            
1         84.0        5  91.0    6      4422  
2         86.0        6  83.0    4      3432  
3         85.0        4  95.0    5      4066  
4        105.0        5  97.0    6      4322  
5         76.0        2  64.0    4      3031

In [156]:
X_test_new = df2.values[:,:]

In [157]:
X_test_new.shape

(3299, 12)

In [158]:
X_test_new = scaler.transform(X_test_new)

In [167]:
Y_pred=svc_model.predict(X_test_new)

In [168]:
print(Y_pred)

[1. 3. 2. ... 2. 3. 3.]


In [161]:
#model_RandomForest.score(X_train,Y_train)

In [172]:
#USEING SVC MODEL 
svc_model.score(X_train,Y_train)
#0.9958095238095238
#0.9784761904761905
#0.9958095238095238
 #0.9017142857142857
    
"""The best accuracy by using svc_medel & and hyperparameter are used kernel='rbf',C=10,gamma=0.1"""

"The best accuracy by using svc_medel & and hyperparameter are used kernel='rbf',C=10,gamma=0.1"

In [163]:
testnew=pd.read_csv(r'C:\Users\neeraj nandkumar\downloads\TEST_.csv')
#
testnew["PREDICTION"]=Y_pred
testnew.head()

id  Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  \
0   1          348    9.0        5.0          3.0           5  NaN   
1   2          311    6.0        5.0          5.0           6   NO   
2   3          342    5.0        6.0          6.0           7  yes   
3   4          329    7.0        7.0          4.0           6  NaN   
4   5          307    6.0        2.0          3.0           4   no   

   Roof(Area)  Lawn(Area)  Nfloors   API  ANB EXPECTED  PREDICTION  
0         NaN        84.0        5  91.0    6    4422$         1.0  
1         0.0        86.0        6  83.0    4    3432$         3.0  
2       120.0        85.0        4  95.0    5    4066$         2.0  
3         NaN       105.0        5  97.0    6    4322$         2.0  
4         0.0        76.0        2  64.0    4    3031$         3.0

In [164]:
testnew.PREDICTION=testnew.PREDICTION.map({0.0:"A",1.0:"B",2.0:"C",3.0:"D",4.0:"E"})
testnew.head()

id  Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  \
0   1          348    9.0        5.0          3.0           5  NaN   
1   2          311    6.0        5.0          5.0           6   NO   
2   3          342    5.0        6.0          6.0           7  yes   
3   4          329    7.0        7.0          4.0           6  NaN   
4   5          307    6.0        2.0          3.0           4   no   

   Roof(Area)  Lawn(Area)  Nfloors   API  ANB EXPECTED PREDICTION  
0         NaN        84.0        5  91.0    6    4422$          B  
1         0.0        86.0        6  83.0    4    3432$          D  
2       120.0        85.0        4  95.0    5    4066$          C  
3         NaN       105.0        5  97.0    6    4322$          C  
4         0.0        76.0        2  64.0    4    3031$          D

#### To save predicted file in the system as extension.CSV

In [173]:
#testnew.to_csv("FILE17.csv")